version: '3.8'

services:
  redis:
    image: redis:alpine

  web:
    build: .
    command: python scraper_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A scraper_project worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis 