apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  REDIS_URL: "redis://redis-service:6379/0"
  DJANGO_SETTINGS_MODULE: "scraper_project.settings" 