apiVersion: v1
kind: Service
metadata:
  name: {{ include "fleek-scraper.fullname" . }}-web
  labels:
    {{- include "fleek-scraper.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.service.web.type }}
  ports:
  - port: {{ .Values.service.web.port }}
    targetPort: {{ .Values.service.web.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "fleek-scraper.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web 